# Generated by Django 5.2.5 on 2026-01-06 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('event', 'Event'), ('task', 'Task'), ('meeting', 'Meeting'), ('scheduled', 'Scheduled'), ('task_reminder', 'Task Reminder')], default='event', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(editable=False, null=True)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('meeting_id', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('color_code', models.CharField(default='#22c55e', max_length=7)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_all_day', models.BooleanField(default=False)),
                ('reminder_minutes', models.IntegerField(blank=True, help_text='Minutes before event to trigger reminder', null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attending_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_datetime', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='calendar_module.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reminder_datetime'],
            },
        ),
        migrations.CreateModel(
            name='RecurringEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Repeat every X days/weeks/months')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('occurrences', models.PositiveIntegerField(blank=True, null=True)),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='Weekday numbers (0=Monday, 6=Sunday)')),
                ('base_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='calendar_module.calendarevent')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='calendar_mo_start_d_e894c9_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_type'], name='calendar_mo_event_t_407a10_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['created_by'], name='calendar_mo_created_b5743d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventreminder',
            unique_together={('event', 'user', 'reminder_datetime')},
        ),
    ]
